-- ============================================================================
-- Home del ecommerce: "destacados", "ofertas con vigencia" y "banners".
-- ============================================================================
-- Todo esto se administra desde acá (proyecto-joyeria): el ecommerce solo lee
-- vía las RPC de solo lectura ecommerce_* (ver joyeria-ecommerce/supabase),
-- nunca escribe estas tablas directo.
--
-- destacado / precio_oferta / oferta_desde / oferta_hasta se agregan a
-- `productos`: aplican tanto a productos normales (precio_venta directo)
-- como a diseños de joyería, aunque para joyería el precio real de venta
-- vive en la pieza/variante, no en `productos.precio_venta` — la oferta de
-- un diseño de joyería queda como dato informativo hasta que exista ese caso
-- de uso real (backlog).
--
-- `banners` es tabla nueva, sin RLS y con GRANT total a anon/authenticated
-- (mismo criterio ya usado en productos/producto_imagenes: la tabla en sí
-- queda abierta, el gate real es que el ecommerce nunca la lee directo,
-- siempre pasa por ecommerce_listar_banners).
-- ============================================================================

ALTER TABLE public.productos
  ADD COLUMN IF NOT EXISTS destacado boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS precio_oferta numeric NULL,
  ADD COLUMN IF NOT EXISTS oferta_desde timestamp with time zone NULL,
  ADD COLUMN IF NOT EXISTS oferta_hasta timestamp with time zone NULL;

ALTER TABLE public.productos
  ADD CONSTRAINT productos_oferta_vigencia_check
  CHECK (
    oferta_desde IS NULL OR oferta_hasta IS NULL OR oferta_hasta > oferta_desde
  );

COMMENT ON COLUMN public.productos.destacado IS
  'Si aparece en la vitrina "Productos destacados" del home del ecommerce.';
COMMENT ON COLUMN public.productos.precio_oferta IS
  'Precio con descuento (NULL = sin oferta). Vigente solo dentro de oferta_desde/oferta_hasta cuando están definidas.';


-- ----------------------------------------------------------------------------
-- Tabla de banners del home del ecommerce (hero rotativo).
-- ----------------------------------------------------------------------------
CREATE TABLE public.banners (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empresa   bigint NOT NULL,
  titulo       text NOT NULL,
  subtitulo    text,
  imagen_url   text NOT NULL,
  imagen_path  text NOT NULL,
  link_destino text,
  orden        integer NOT NULL DEFAULT 0,
  activo       boolean NOT NULL DEFAULT true,
  created_at   timestamp with time zone NOT NULL DEFAULT now(),
  updated_at   timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.banners
  ADD CONSTRAINT banners_id_empresa_fkey
  FOREIGN KEY (id_empresa) REFERENCES public.empresa(id) ON DELETE CASCADE;

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE
  ON TABLE public.banners TO anon, authenticated, postgres, service_role;

GRANT USAGE, SELECT ON SEQUENCE public.banners_id_seq
  TO anon, authenticated, postgres, service_role;

COMMENT ON TABLE public.banners IS
  'Banners del hero del home del ecommerce. Administrados desde proyecto-joyeria (Productos → Banners); leídos por joyeria-ecommerce vía ecommerce_listar_banners.';


-- ----------------------------------------------------------------------------
-- insertarproductos / editarproductos: agregar los 4 campos nuevos con
-- DEFAULT para no romper llamadas existentes (PostgREST matchea por nombre).
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.insertarproductos (
  _nombre              text,
  _precio_venta        numeric,
  _precio_compra       numeric,
  _id_categoria        integer,
  _codigo_barras       text,
  _codigo_interno      text,
  _id_empresa          integer,
  _sevende_por         text,
  _maneja_inventarios  boolean,
  _maneja_multiprecios boolean,
  _destacado           boolean DEFAULT false,
  _precio_oferta       numeric DEFAULT NULL,
  _oferta_desde        timestamp with time zone DEFAULT NULL,
  _oferta_hasta        timestamp with time zone DEFAULT NULL
)
  RETURNS integer
  LANGUAGE plpgsql
  AS $function$
declare nuevo_id int;
begin
 perform 1 from productos where nombre=_nombre and id_empresa=_id_empresa and activo;
 if found then
   raise exception 'Nombre de producto duplicado';
 else
    perform 1 from productos where (codigo_interno=_codigo_interno or codigo_barras=_codigo_barras)
     and id_empresa=_id_empresa and activo;
    if found then
     raise exception 'Codigo de barra ó interno duplicado';
    else
     insert into productos(
       nombre,precio_venta,precio_compra,id_categoria,codigo_barras,codigo_interno,
       id_empresa,sevende_por,maneja_inventarios,maneja_multiprecios,
       destacado,precio_oferta,oferta_desde,oferta_hasta
     )
     values(
       _nombre,_precio_venta,_precio_compra,_id_categoria,_codigo_barras,_codigo_interno,
       _id_empresa,_sevende_por,_maneja_inventarios,_maneja_multiprecios,
       _destacado,_precio_oferta,_oferta_desde,_oferta_hasta
     )
     returning id into nuevo_id;
     return nuevo_id;
     end if;
  end if;
end;
$function$;

CREATE OR REPLACE FUNCTION public.editarproductos (
  _id                 integer,
  _nombre             text,
  _precio_venta       numeric,
  _precio_compra      numeric,
  _id_categoria       integer,
  _codigo_barras      text,
  _codigo_interno     text,
  _id_empresa         integer,
  _sevende_por        text,
  _maneja_inventarios boolean,
  _destacado          boolean DEFAULT false,
  _precio_oferta      numeric DEFAULT NULL,
  _oferta_desde       timestamp with time zone DEFAULT NULL,
  _oferta_hasta       timestamp with time zone DEFAULT NULL
)
  RETURNS void
  LANGUAGE plpgsql
  AS $function$
begin
 perform 1 from productos where nombre=_nombre and id_empresa=_id_empresa and id!=_id and activo;
 if found then
   raise exception 'Nombre de producto duplicado';
 else
    perform 1 from productos where ((codigo_interno=_codigo_interno and id_empresa=_id_empresa and id!=_id) or
    (codigo_barras=_codigo_barras and id_empresa=_id_empresa and id!=_id)) and activo;
    if found then
     raise exception 'Codigo de barra ó interno duplicado';
    else
     update productos set
       nombre=_nombre,precio_venta=_precio_venta,precio_compra=_precio_compra,
       id_categoria=_id_categoria,codigo_barras=_codigo_barras,codigo_interno=_codigo_interno,
       sevende_por=_sevende_por,maneja_inventarios=_maneja_inventarios,
       destacado=_destacado,precio_oferta=_precio_oferta,
       oferta_desde=_oferta_desde,oferta_hasta=_oferta_hasta,
       updated_at=now()
     where id=_id;
     end if;
  end if;
end;
$function$;


-- ----------------------------------------------------------------------------
-- crear_producto_joyeria: solo agrega `_destacado` (el diseño de joyería no
-- maneja precio propio, ese vive en la variante/pieza).
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.crear_producto_joyeria (
  _nombre       text,
  _descripcion  text,
  _id_categoria integer,
  _id_marca     integer,
  _id_empresa   integer,
  _destacado    boolean DEFAULT false
)
  RETURNS integer
  LANGUAGE plpgsql
  AS $function$
DECLARE nuevo_id int;
BEGIN
  IF _nombre IS NULL OR btrim(_nombre) = '' THEN
    RAISE EXCEPTION 'El nombre del producto es obligatorio';
  END IF;

  PERFORM 1 FROM productos WHERE nombre = _nombre AND id_empresa = _id_empresa;
  IF FOUND THEN
    RAISE EXCEPTION 'Nombre de producto duplicado';
  END IF;

  INSERT INTO productos (
    nombre, descripcion, precio_venta, precio_compra, id_categoria, id_marca,
    id_empresa, sevende_por, maneja_inventarios, maneja_multiprecios, es_joyeria,
    destacado
  ) VALUES (
    _nombre, _descripcion, 0, 0, _id_categoria, _id_marca,
    _id_empresa, 'unidad', false, false, true,
    _destacado
  )
  RETURNING id INTO nuevo_id;

  RETURN nuevo_id;
END;
$function$;
