-- ============================================================================
-- Catálogo: ficha técnica completa (etiquetas, medidas, tallas, marca).
-- ============================================================================
-- Cierra el checklist de "Catálogo de productos". Todo se administra desde
-- proyecto-joyeria (panel) y el ecommerce solo lee vía RPC ecommerce_*.
--
--   - `etiquetas` + `producto_etiquetas`: tags N:M por producto. Tabla sin
--     RLS y GRANT total a anon/authenticated (mismo criterio que `banners`
--     y `producto_imagenes`): el gate real es que el ecommerce nunca las lee
--     directo, siempre pasa por ecommerce_listar_etiquetas / _listar_productos.
--   - `productos.medidas` / `productos.tallas`: texto libre informativo.
--   - `piezas_inventario.talla`: talle real de la pieza física (ej. anillo).
--   - `insertarproductos` / `editarproductos`: se agregan `_id_marca`,
--     `_medidas`, `_tallas` como parámetros nuevos con DEFAULT (mismo patrón
--     que 20260909180000 con `_destacado` — PostgREST matchea por nombre, las
--     llamadas viejas siguen funcionando).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1) Etiquetas (tags N:M)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.etiquetas (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empresa bigint NOT NULL,
  nombre     text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT etiquetas_id_empresa_fkey FOREIGN KEY (id_empresa)
    REFERENCES public.empresa(id) ON DELETE CASCADE,
  CONSTRAINT etiquetas_nombre_uq UNIQUE (id_empresa, nombre)
);

CREATE TABLE IF NOT EXISTS public.producto_etiquetas (
  id_producto bigint NOT NULL REFERENCES public.productos(id) ON DELETE CASCADE,
  id_etiqueta bigint NOT NULL REFERENCES public.etiquetas(id) ON DELETE CASCADE,
  PRIMARY KEY (id_producto, id_etiqueta)
);

CREATE INDEX IF NOT EXISTS producto_etiquetas_id_etiqueta_idx
  ON public.producto_etiquetas (id_etiqueta);

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE
  ON TABLE public.etiquetas TO anon, authenticated, postgres, service_role;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE
  ON TABLE public.producto_etiquetas TO anon, authenticated, postgres, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.etiquetas_id_seq
  TO anon, authenticated, postgres, service_role;

COMMENT ON TABLE public.etiquetas IS
  'Etiquetas/tags de producto. Administradas desde proyecto-joyeria; leídas por el ecommerce vía ecommerce_listar_etiquetas.';


-- ----------------------------------------------------------------------------
-- 2) Columnas nuevas de ficha técnica
-- ----------------------------------------------------------------------------
ALTER TABLE public.productos
  ADD COLUMN IF NOT EXISTS medidas text NULL,
  ADD COLUMN IF NOT EXISTS tallas  text NULL;

ALTER TABLE public.piezas_inventario
  ADD COLUMN IF NOT EXISTS talla text NULL;

COMMENT ON COLUMN public.productos.medidas IS
  'Medidas/dimensiones del producto, texto libre (ej. "45 cm largo / 3 mm ancho").';
COMMENT ON COLUMN public.productos.tallas IS
  'Tallas disponibles para productos no serializados, texto libre (ej. "6, 7, 8, 9").';
COMMENT ON COLUMN public.piezas_inventario.talla IS
  'Talle de la pieza física serializada (ej. talla de anillo). NULL si no aplica.';


-- ----------------------------------------------------------------------------
-- 3) Admin (proyecto-joyeria): CRUD de etiquetas
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.listar_etiquetas(_id_empresa integer)
RETURNS TABLE (id bigint, nombre text)
LANGUAGE sql
STABLE
AS $$
  SELECT e.id, e.nombre
  FROM etiquetas e
  WHERE e.id_empresa = _id_empresa
  ORDER BY e.nombre;
$$;

CREATE OR REPLACE FUNCTION public.insertar_etiqueta(_nombre text, _id_empresa integer)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE nuevo_id bigint;
BEGIN
  IF _nombre IS NULL OR btrim(_nombre) = '' THEN
    RAISE EXCEPTION 'El nombre de la etiqueta es obligatorio';
  END IF;
  INSERT INTO etiquetas (nombre, id_empresa)
  VALUES (btrim(_nombre), _id_empresa)
  ON CONFLICT (id_empresa, nombre) DO UPDATE SET nombre = EXCLUDED.nombre
  RETURNING id INTO nuevo_id;
  RETURN nuevo_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.eliminar_etiqueta(_id integer)
RETURNS void
LANGUAGE sql
AS $$
  DELETE FROM etiquetas WHERE id = _id;
$$;

-- Reemplaza el set completo de etiquetas de un producto (patrón "replace all").
CREATE OR REPLACE FUNCTION public.set_etiquetas_producto(
  _id_producto integer,
  _ids_etiquetas bigint[]
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  DELETE FROM producto_etiquetas WHERE id_producto = _id_producto;
  IF _ids_etiquetas IS NOT NULL AND array_length(_ids_etiquetas, 1) IS NOT NULL THEN
    INSERT INTO producto_etiquetas (id_producto, id_etiqueta)
    SELECT _id_producto, x
    FROM unnest(_ids_etiquetas) AS x
    ON CONFLICT DO NOTHING;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.etiquetas_de_producto(_id_producto integer)
RETURNS TABLE (id bigint, nombre text)
LANGUAGE sql
STABLE
AS $$
  SELECT e.id, e.nombre
  FROM producto_etiquetas pe
  JOIN etiquetas e ON e.id = pe.id_etiqueta
  WHERE pe.id_producto = _id_producto
  ORDER BY e.nombre;
$$;

GRANT EXECUTE ON FUNCTION public.listar_etiquetas(integer) TO anon, authenticated, postgres, service_role;
GRANT EXECUTE ON FUNCTION public.insertar_etiqueta(text, integer) TO anon, authenticated, postgres, service_role;
GRANT EXECUTE ON FUNCTION public.eliminar_etiqueta(integer) TO anon, authenticated, postgres, service_role;
GRANT EXECUTE ON FUNCTION public.set_etiquetas_producto(integer, bigint[]) TO anon, authenticated, postgres, service_role;
GRANT EXECUTE ON FUNCTION public.etiquetas_de_producto(integer) TO anon, authenticated, postgres, service_role;


-- ----------------------------------------------------------------------------
-- 4) Admin: insertarproductos / editarproductos + _id_marca, _medidas, _tallas
--    (overload nuevo con DEFAULT; el form de proyecto-joyeria pasa las claves
--    nuevas, las llamadas viejas siguen resolviendo al overload anterior).
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.insertarproductos (
  _nombre              text,
  _precio_venta        numeric,
  _precio_compra       numeric,
  _id_categoria        integer,
  _codigo_barras       text,
  _codigo_interno      text,
  _id_empresa          integer,
  _sevende_por         text,
  _maneja_inventarios  boolean,
  _maneja_multiprecios boolean,
  _destacado           boolean DEFAULT false,
  _precio_oferta       numeric DEFAULT NULL,
  _oferta_desde        timestamp with time zone DEFAULT NULL,
  _oferta_hasta        timestamp with time zone DEFAULT NULL,
  _id_marca            bigint DEFAULT NULL,
  _medidas             text DEFAULT NULL,
  _tallas              text DEFAULT NULL
)
  RETURNS integer
  LANGUAGE plpgsql
  AS $function$
declare nuevo_id int;
begin
 perform 1 from productos where nombre=_nombre and id_empresa=_id_empresa and activo;
 if found then
   raise exception 'Nombre de producto duplicado';
 else
    perform 1 from productos where (codigo_interno=_codigo_interno or codigo_barras=_codigo_barras)
     and id_empresa=_id_empresa and activo;
    if found then
     raise exception 'Codigo de barra ó interno duplicado';
    else
     insert into productos(
       nombre,precio_venta,precio_compra,id_categoria,codigo_barras,codigo_interno,
       id_empresa,sevende_por,maneja_inventarios,maneja_multiprecios,
       destacado,precio_oferta,oferta_desde,oferta_hasta,
       id_marca,medidas,tallas
     )
     values(
       _nombre,_precio_venta,_precio_compra,_id_categoria,_codigo_barras,_codigo_interno,
       _id_empresa,_sevende_por,_maneja_inventarios,_maneja_multiprecios,
       _destacado,_precio_oferta,_oferta_desde,_oferta_hasta,
       _id_marca,_medidas,_tallas
     )
     returning id into nuevo_id;
     return nuevo_id;
     end if;
  end if;
end;
$function$;

CREATE OR REPLACE FUNCTION public.editarproductos (
  _id                 integer,
  _nombre             text,
  _precio_venta       numeric,
  _precio_compra      numeric,
  _id_categoria       integer,
  _codigo_barras      text,
  _codigo_interno     text,
  _id_empresa         integer,
  _sevende_por        text,
  _maneja_inventarios boolean,
  _destacado          boolean DEFAULT false,
  _precio_oferta      numeric DEFAULT NULL,
  _oferta_desde       timestamp with time zone DEFAULT NULL,
  _oferta_hasta       timestamp with time zone DEFAULT NULL,
  _id_marca           bigint DEFAULT NULL,
  _medidas            text DEFAULT NULL,
  _tallas             text DEFAULT NULL
)
  RETURNS void
  LANGUAGE plpgsql
  AS $function$
begin
 perform 1 from productos where nombre=_nombre and id_empresa=_id_empresa and id!=_id and activo;
 if found then
   raise exception 'Nombre de producto duplicado';
 else
    perform 1 from productos where ((codigo_interno=_codigo_interno and id_empresa=_id_empresa and id!=_id) or
    (codigo_barras=_codigo_barras and id_empresa=_id_empresa and id!=_id)) and activo;
    if found then
     raise exception 'Codigo de barra ó interno duplicado';
    else
     update productos set
       nombre=_nombre,precio_venta=_precio_venta,precio_compra=_precio_compra,
       id_categoria=_id_categoria,codigo_barras=_codigo_barras,codigo_interno=_codigo_interno,
       sevende_por=_sevende_por,maneja_inventarios=_maneja_inventarios,
       destacado=_destacado,precio_oferta=_precio_oferta,
       oferta_desde=_oferta_desde,oferta_hasta=_oferta_hasta,
       id_marca=_id_marca,medidas=_medidas,tallas=_tallas,
       updated_at=now()
     where id=_id;
     end if;
  end if;
end;
$function$;

GRANT EXECUTE ON FUNCTION public.insertarproductos(text, numeric, numeric, integer, text, text, integer, text, boolean, boolean, boolean, numeric, timestamp with time zone, timestamp with time zone, bigint, text, text)
  TO PUBLIC, anon, authenticated, postgres, service_role;
GRANT EXECUTE ON FUNCTION public.editarproductos(integer, text, numeric, numeric, integer, text, text, integer, text, boolean, boolean, numeric, timestamp with time zone, timestamp with time zone, bigint, text, text)
  TO PUBLIC, anon, authenticated, postgres, service_role;


-- ----------------------------------------------------------------------------
-- 5) Ecommerce (solo lectura): reexponer catálogo con marca + etiquetas +
--    medidas + tallas. RETURNS TABLE cambia -> DROP + CREATE.
-- ----------------------------------------------------------------------------

-- 5.1) Etiquetas del catálogo público (empresa fija del ecommerce).
CREATE OR REPLACE FUNCTION public.ecommerce_listar_etiquetas()
RETURNS TABLE (id bigint, nombre text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT e.id, e.nombre
  FROM etiquetas e
  WHERE e.id_empresa = public.ecommerce_id_empresa()
  ORDER BY e.nombre;
$$;

GRANT EXECUTE ON FUNCTION public.ecommerce_listar_etiquetas() TO anon, authenticated, service_role;


-- 5.2) Listado: agrega `etiquetas text[]` y el filtro `_id_etiqueta`.
DROP FUNCTION IF EXISTS public.ecommerce_listar_productos(integer, text, numeric, numeric, text, integer, integer);

CREATE OR REPLACE FUNCTION public.ecommerce_listar_productos(
  _id_categoria integer DEFAULT NULL,
  _material text DEFAULT NULL,
  _precio_min numeric DEFAULT NULL,
  _precio_max numeric DEFAULT NULL,
  _buscador text DEFAULT NULL,
  _pagina integer DEFAULT 1,
  _tam_pagina integer DEFAULT 24,
  _id_etiqueta bigint DEFAULT NULL
)
RETURNS TABLE (
  id bigint,
  nombre text,
  descripcion text,
  precio_venta numeric,
  id_categoria bigint,
  categoria text,
  es_joyeria boolean,
  imagen_portada text,
  total_disponible numeric,
  destacado boolean,
  precio_oferta numeric,
  marca text,
  etiquetas text[],
  total_count bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH base AS (
    SELECT
      p.id, p.nombre, p.descripcion, p.precio_venta, p.id_categoria,
      c.nombre AS categoria, p.es_joyeria,
      (
        SELECT pi.url FROM producto_imagenes pi
        WHERE pi.id_producto = p.id
        ORDER BY pi.orden ASC LIMIT 1
      ) AS imagen_portada,
      CASE
        WHEN p.es_joyeria THEN (
          SELECT count(*)::numeric FROM piezas_inventario pz
          WHERE pz.id_producto = p.id AND pz.estado = 'disponible'
        )
        WHEN p.maneja_inventarios THEN (
          SELECT COALESCE(sum(s.stock), 0) FROM stock s
          WHERE s.id_producto = p.id
        )
        ELSE NULL
      END AS total_disponible,
      p.destacado,
      CASE
        WHEN p.precio_oferta IS NOT NULL
         AND (p.oferta_desde IS NULL OR now() >= p.oferta_desde)
         AND (p.oferta_hasta IS NULL OR now() <= p.oferta_hasta)
        THEN p.precio_oferta
        ELSE NULL
      END AS precio_oferta,
      (SELECT m.nombre FROM marca m WHERE m.id = p.id_marca) AS marca,
      COALESCE((
        SELECT array_agg(e.nombre ORDER BY e.nombre)
        FROM producto_etiquetas pe
        JOIN etiquetas e ON e.id = pe.id_etiqueta
        WHERE pe.id_producto = p.id
      ), '{}') AS etiquetas
    FROM productos p
    JOIN categorias c ON c.id = p.id_categoria
    WHERE p.id_empresa = public.ecommerce_id_empresa()
      AND p.activo = true
      AND (_id_categoria IS NULL OR p.id_categoria = _id_categoria)
      AND (_precio_min IS NULL OR p.precio_venta >= _precio_min)
      AND (_precio_max IS NULL OR p.precio_venta <= _precio_max)
      AND (_buscador IS NULL OR p.nombre ILIKE '%' || _buscador || '%')
      AND (
        _material IS NULL OR EXISTS (
          SELECT 1 FROM producto_variantes v
          WHERE v.id_producto = p.id AND v.material ILIKE _material
        )
      )
      AND (
        _id_etiqueta IS NULL OR EXISTS (
          SELECT 1 FROM producto_etiquetas pe
          WHERE pe.id_producto = p.id AND pe.id_etiqueta = _id_etiqueta
        )
      )
  )
  SELECT
    b.id, b.nombre, b.descripcion, b.precio_venta, b.id_categoria, b.categoria,
    b.es_joyeria, b.imagen_portada, b.total_disponible, b.destacado, b.precio_oferta,
    b.marca, b.etiquetas,
    count(*) OVER() AS total_count
  FROM base b
  ORDER BY b.nombre ASC
  LIMIT GREATEST(_tam_pagina, 1)
  OFFSET GREATEST(_pagina - 1, 0) * GREATEST(_tam_pagina, 1);
$$;

GRANT EXECUTE ON FUNCTION public.ecommerce_listar_productos(integer, text, numeric, numeric, text, integer, integer, bigint)
  TO anon, authenticated, service_role;


-- 5.3) Detalle: agrega medidas, tallas y etiquetas.
DROP FUNCTION IF EXISTS public.ecommerce_producto_detalle(integer);

CREATE OR REPLACE FUNCTION public.ecommerce_producto_detalle(_id_producto integer)
RETURNS TABLE (
  id bigint,
  nombre text,
  descripcion text,
  id_categoria bigint,
  categoria text,
  es_joyeria boolean,
  precio_venta numeric,
  imagen_portada text,
  total_disponible numeric,
  destacado boolean,
  precio_oferta numeric,
  marca text,
  medidas text,
  tallas text,
  etiquetas text[]
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT
    p.id, p.nombre, p.descripcion, p.id_categoria, c.nombre, p.es_joyeria, p.precio_venta,
    (
      SELECT pi.url FROM producto_imagenes pi
      WHERE pi.id_producto = p.id
      ORDER BY pi.orden ASC LIMIT 1
    ) AS imagen_portada,
    CASE
      WHEN p.es_joyeria THEN (
        SELECT count(*)::numeric FROM piezas_inventario pz
        WHERE pz.id_producto = p.id AND pz.estado = 'disponible'
      )
      WHEN p.maneja_inventarios THEN (
        SELECT COALESCE(sum(s.stock), 0) FROM stock s
        WHERE s.id_producto = p.id
      )
      ELSE NULL
    END AS total_disponible,
    p.destacado,
    CASE
      WHEN p.precio_oferta IS NOT NULL
       AND (p.oferta_desde IS NULL OR now() >= p.oferta_desde)
       AND (p.oferta_hasta IS NULL OR now() <= p.oferta_hasta)
      THEN p.precio_oferta
      ELSE NULL
    END AS precio_oferta,
    (SELECT m.nombre FROM marca m WHERE m.id = p.id_marca) AS marca,
    p.medidas,
    p.tallas,
    COALESCE((
      SELECT array_agg(e.nombre ORDER BY e.nombre)
      FROM producto_etiquetas pe
      JOIN etiquetas e ON e.id = pe.id_etiqueta
      WHERE pe.id_producto = p.id
    ), '{}') AS etiquetas
  FROM productos p
  JOIN categorias c ON c.id = p.id_categoria
  WHERE p.id = _id_producto
    AND p.id_empresa = public.ecommerce_id_empresa()
    AND p.activo = true;
$$;

GRANT EXECUTE ON FUNCTION public.ecommerce_producto_detalle(integer) TO anon, authenticated, service_role;


-- 5.4) Variantes: agrega `tallas_disponibles` (distinct de las piezas libres).
DROP FUNCTION IF EXISTS public.ecommerce_variantes_disponibles(integer);

CREATE OR REPLACE FUNCTION public.ecommerce_variantes_disponibles(_id_producto integer)
RETURNS TABLE (
  id_variante bigint,
  material text,
  pureza text,
  precio_venta_sugerido numeric,
  imagen_portada text,
  piezas_disponibles bigint,
  tallas_disponibles text[]
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT
    v.id AS id_variante,
    v.material,
    v.pureza,
    v.precio_venta_sugerido,
    (
      SELECT vi.url FROM producto_variante_imagenes vi
      WHERE vi.id_variante = v.id
      ORDER BY vi.orden ASC LIMIT 1
    ) AS imagen_portada,
    count(pz.id) FILTER (WHERE pz.estado = 'disponible') AS piezas_disponibles,
    COALESCE((
      SELECT array_agg(DISTINCT pz2.talla ORDER BY pz2.talla)
      FROM piezas_inventario pz2
      WHERE pz2.id_variante = v.id AND pz2.estado = 'disponible' AND pz2.talla IS NOT NULL
    ), '{}') AS tallas_disponibles
  FROM producto_variantes v
  JOIN productos p ON p.id = v.id_producto
  LEFT JOIN piezas_inventario pz ON pz.id_variante = v.id AND pz.estado = 'disponible'
  WHERE v.id_producto = _id_producto
    AND p.id_empresa = public.ecommerce_id_empresa()
    AND p.activo = true
  GROUP BY v.id, v.material, v.pureza, v.precio_venta_sugerido
  ORDER BY v.material, v.pureza;
$$;

GRANT EXECUTE ON FUNCTION public.ecommerce_variantes_disponibles(integer) TO anon, authenticated, service_role;


-- 5.5) Piezas de una variante: agrega `talla`.
DROP FUNCTION IF EXISTS public.ecommerce_piezas_disponibles(bigint);

CREATE OR REPLACE FUNCTION public.ecommerce_piezas_disponibles(_id_variante bigint)
RETURNS TABLE (id_pieza bigint, sku text, peso numeric, precio_venta numeric, talla text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT pz.id, pz.sku, pz.peso, pz.precio_venta, pz.talla
  FROM piezas_inventario pz
  WHERE pz.id_variante = _id_variante
    AND pz.id_empresa = public.ecommerce_id_empresa()
    AND pz.estado = 'disponible'
  ORDER BY pz.precio_venta ASC;
$$;

GRANT EXECUTE ON FUNCTION public.ecommerce_piezas_disponibles(bigint) TO anon, authenticated, service_role;
